### ISSUE TITLE
Bring back the children

### ISSUE THREAD

**Issue by staudlol** [crafted-mc/krafted#1]
change from 'workerGroup' in the Server class to 'childrenGroup'

**Comment by therealnv6** [comment]
Yes

**Comment by pcranaway** [comment]
@staudlol, The children are still here.
```kotlin
val bootstrap = ServerBootstrap().apply {
    this.group(bossGroup, workerGroup)
    this.channel(NioServerSocketChannel::class.java)
    this.handler(LoggingHandler(LogLevel.DEBUG))
    this.childHandler(ServerInitializer)
}
```

**Comment by therealnv6** [comment]
val bootstrap = ServerBootstrap().apply {
    this.group(bossGroup, workerGroup)
    this.channel(NioServerSocketChannel::class.java)
    this.handler(LoggingHandler(LogLevel.DEBUG))
    this.childHandler(ServerInitializer)
}
